# permissions for end users to edit operatorupgraderequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lifecycle-operator
    app.kubernetes.io/managed-by: kustomize
  name: operatorupgraderequest-editor-role
rules:
- apiGroups:
  - lifecycle.tldr.cloud
  resources:
  - operatorupgraderequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.tldr.cloud
  resources:
  - operatorupgraderequests/status
  verbs:
  - get
