---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lifecycle.tldr.cloud
  resources:
  - operatorupgraderequests
  - watchedoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.tldr.cloud
  resources:
  - operatorupgraderequests/finalizers
  - watchedoperators/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.tldr.cloud
  resources:
  - operatorupgraderequests/status
  - watchedoperators/status
  verbs:
  - get
  - patch
  - update
